//go:build ignore
// +build ignore

package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/format"
	"html/template"
	"io"
	"log"
	"net/http"
	"os"
	"time"

	"golang.org/x/crypto/x509roots"
)

var tmpl = template.Must(template.New("bundle.go").Parse(`// Code generated by gen.go at {{.Time}}; DO NOT EDIT.

package fallback

import "crypto/x509"

func mustParse(b []byte) *x509.Certificate {
	c, err := x509.ParseCertificate(b)
	if err != nil {
		panic(err)
	}
	return c
}

var bundle = []*x509.Certificate{ {{range .Certs}}
	// {{.Subject}}
	mustParse({{.Bytes}}),
{{end}}
}`))

var (
	certDataURL  = flag.String("certdata-url", "https://hg.mozilla.org/mozilla-central/raw-file/tip/security/nss/lib/ckfw/builtins/certdata.txt", "URL to the raw certdata.txt file to parse (only one of certdata-url and certdata-path may be specified)")
	certDataPath = flag.String("certdata-path", "", "Path to the NSS certdata.txt file to parse (only one of certdata-url and certdata-path may be specified)")
	output       = flag.String("output", "bundle.go", "Path to file to write output to")
)

func main() {
	if *certDataPath != "" && *certDataURL != "" {
		log.Fatal("Only one of --certdata-url and --certdata-path may be supplied")
	}

	var certdata io.Reader

	if *certDataPath != "" {
		f, err := os.Open(*certDataPath)
		if err != nil {
			log.Fatalf("unable to open %q: %s", *certDataPath, err)
		}
		defer f.Close()
		certdata = f
	} else {
		resp, err := http.Get(*certDataURL)
		if err != nil {
			log.Fatal("failed to request %q: %s", *certDataURL, err)
		}
		defer resp.Body.Close()
		certdata = resp.Body
	}

	certs, err := x509roots.ParseNSSCertData(certdata)
	if err != nil {
		log.Fatalf("failed to parse %q: %s", *certDataPath, err)
	}

	type entry struct {
		Subject string
		Bytes   string
	}
	var entries []entry
	for _, c := range certs {
		if c.DistrustAfter != nil {
			// Until the constrained roots API lands, skip anything that has any
			// additional constraints. Once that API is available, we can add
			// build constraints that support both the current version and the
			// new version.
			continue
		}
		entries = append(entries, entry{Subject: c.Certificate.Subject.String(), Bytes: fmt.Sprintf("%#v", c.Certificate.Raw)})
	}

	b := bytes.NewBuffer(nil)
	tmpl.Execute(b, struct {
		Time  string
		Certs []entry
	}{time.Now().Format(time.RFC1123), entries})
	formatted, err := format.Source(b.Bytes())
	if err != nil {
		log.Fatalf("failed to format source: %s", err)
	}

	if err := os.WriteFile(*output, formatted, 0644); err != nil {
		log.Fatalf("failed to write to %q: %s", *output, err)
	}
}
