// Copyright 2015 The Go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package acme

import (
	"encoding/json"
	"fmt"
	"io/ioutil"
	"net/http"
)

// Predefined Error.Type values by the ACME spec.
const (
	ErrBadCSR       = "urn:acme:error:badCSR"
	ErrBadNonce     = "urn:acme:error:badNonce"
	ErrConnection   = "urn:acme:error:connection"
	ErrDNSSec       = "urn:acme:error:dnssec"
	ErrMalformed    = "urn:acme:error:malformed"
	ErrInternal     = "urn:acme:error:serverInternal"
	ErrTLS          = "urn:acme:error:tls"
	ErrUnauthorized = "urn:acme:error:unauthorized"
	ErrUnknownHost  = "urn:acme:error:unknownHost"
	ErrRateLimited  = "urn:acme:error:rateLimited"
)

// Error is an ACME error, defined in Problem Details for HTTP APIs doc
// http://tools.ietf.org/html/draft-ietf-appsawg-http-problem.
type Error struct {
	// Status is The HTTP status code generated by the origin server.
	Status int
	// Type is a URI reference that identifies the problem type.
	// A set of types pre-defined by the ACME spec is provided by this package as ErrXxx.
	Type string
	// Detail is a human readable explanation specific to this occurrence of the problem.
	Detail string
	// Header is the original server error response headers.
	Header http.Header
}

func (e *Error) Error() string {
	return fmt.Sprintf("%d %s: %s", e.Status, e.Type, e.Detail)
}

// responseError creates an error of Error type from resp.
func responseError(resp *http.Response) error {
	// don't care if ReadAll returns an error:
	// json.Unmarshal will fail in that case anyway
	b, _ := ioutil.ReadAll(resp.Body)
	e := &Error{Status: resp.StatusCode, Header: resp.Header}
	if err := json.Unmarshal(b, e); err != nil {
		// this is not a regular error response:
		// populate detail with anything we received,
		// e.Status will already contain HTTP response code value
		e.Detail = string(b)
		if e.Detail == "" {
			e.Detail = resp.Status
		}
	}
	return e
}
